### ISSUE TITLE
Security controller does not have ContentLocale method

### ISSUE THREAD

**Issue by TheBnl** [silverstripe/silverstripe-login-forms#100]
## Affected Version
4.8.0

## Description
When using the module `silverstripe-mfa` I noticed that the translations never kicked in though they were present.
After searching how these would kick in I noticed that the `lang` attribute on the `html` was still empty.
This results from the `Security` class extending the `Controller` class instead of the `ContentController` which has the required method `ContentLocale`

As a temporary fix i've now added the method to the Security trough the following extension:
```php
class SecurityExtension extends Extension
{
    public function ContentLocale()
    {
        $locale = i18n::get_locale();
        return i18n::convert_rfc1766($locale);
    }
}
```

I don't know if it is possible or what the impact would be of extending `Security` on `ContentController`. Otherwist a `ContentLocale` method should be added to `Security`. Or the method should be moved from `ContentController` to the more global `Controller` class.

## PR
- [ ] ~~https://github.com/silverstripe/silverstripe-framework/issues/10081~~
- [x] https://github.com/silverstripe/silverstripe-login-forms/pull/101

**Comment by TheBnl** [comment]
Sounds good, a new Pull is Requested!

**Comment by emteknetnz** [comment]
Linked PR has been merged, I'll close this one now
