### ISSUE TITLE
Show $Content as well as $Form

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-login-forms#14]
When e.g. requesting a password reset email, the content about an email having been sent is inserted to the template via ~`$Message`~ _`$Content`_ as opposed to `$Form` - which the templates currently do not allow for. This means that a user ends up staring at the site Title, and nothing more.

This is not the only flow to follow this pattern - e.g. the change password form has introductory text in the ~`$Message`~ _`$Content`_

![image](https://user-images.githubusercontent.com/778003/56551436-84fe9c80-65dc-11e9-9636-4d1ca14fcf26.png)

**Comment by ScopeyNZ** [comment]
This also affected session messages (see referenced closed issue). I think we should use `$Message` over `$Content` if available; a simple `if $Message elseif $Content` should suffice.

**Comment by NightJar** [comment]
is $Message different from $Form? I thought they were a part of that 🤔 
In any case we should cross reference what happens with the current default templates, and support all that.

**Comment by brynwhyman** [comment]
@NightJar can you confirm this can be closed?

**Comment by NightJar** [comment]
Once #21 is merged, yes :)
