### ISSUE TITLE
Validation messages are not shown as errors

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-login-forms#15]
The following two rules need a third applied also: `.message.validation`

When e.g. the "forgot password" form is filled in and submitted as "admin" the validation error comes back about it not being a valid email address (which is correct), however this is not shown as a validation error style (red text) in line with other error messages on the forms.

Note: In order to recreate this one must first remove `required="required"` via the browser dev tools.

https://github.com/silverstripe/silverstripe-login-forms/blob/4c940de6c901d7e17ae39f08e98388afe8d77560/client/src/styles/forms.scss#L32-L33

**Comment by robbieaverill** [comment]
@Cheddam I feel like I saw code that fixes this issue by supporting `.message` and `.alert` in the templates. Can you confirm?

**Comment by robbieaverill** [comment]
Tested in SS 4.3 and 4.4, both correctly show validation errors on the form (e.g. this is required) and the backend responses (e.g. your password is wrong)
