### ISSUE TITLE
Implement Dark Mode

### ISSUE THREAD

**Issue by Cheddam** [silverstripe/silverstripe-login-forms#16]
The new `prefers-color-scheme` media query has shipped in Safari, with other browsers to follow in the near future. While creating a dark mode for the CMS itself is a significant undertaking that likely won't see the light of day for a while, implementing one for the login UI is a quick win and a good place to start.

**Comment by brynwhyman** [comment]
@Cheddam can you please confirm this is covered in https://github.com/silverstripe/silverstripe-login-forms/issues/23?
