### ISSUE TITLE
Default UI for user without CMS access looks broken logging in

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-login-forms#28]
If a user account is created without permissions to access CMS (e.g. added to admin group), user ends up seeing an unstyled UI after submitting login details

![Logging without CMS access.png](https://images.zenhubusercontent.com/596d365561b4ca3b0a74bd86/d257fccc-c0a0-4a52-81c4-21854ea0c40a)

**Comment by robbieaverill** [comment]
Did you experience this with the demo site we gave you? That site doesn't have any frontend themes configured, which would explain this

**Comment by robbieaverill** [comment]
This is a theme issue, it looks fine with the starter theme:

![Uploading image.png…]()
