### ISSUE TITLE
[Demo issue] Cannot change password

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-login-forms#31]
When changing my temporary password set by my admin when first logging in, from mfaDemo2019 to Hellodemo@2019, I get an error saying to add an Uppercase and punctuation to my password. 

Maybe it's too similar to the previous password?

View issue: http://app.toyboxsystems.com/magic/qtfyB2jxqVYT

**Update**: this issue occurs for new users that are required to change their passwords on Cluster2-uat as well

**Comment by robbieaverill** [comment]
Cannot reproduce with the latest version of 4.0.x-dev, using your example passwords. Feel free to reopen if this is still happening for you @newleeland.
