### ISSUE TITLE
Improve layout styles to improve compatability with different logo sizes

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-login-forms#50]
When following the instructions in the docs to add a custom logo, the current layout styles are not very accommodating to different logo sizes or proportions resulting in the logo often displaying badly and requiring manual CSS adjustments in order to make it work.

Can I suggest adjusting the layout styles to set maximum widths and heights for any logo image, and to also automatically adjust the height of the logo grid cell appropriately, rather than setting it to fixed height in a CSS variable? This would then allow developers to much more easily add a custom logo.

e.g. currently, you end up with something like this:
![](http://spdr.me/Ng0lQk+)

But if we set the height of the cell to `auto` instead of `calc(var(--sizing-app-brand-height) + (var(--spacing-app-brand) * 2))` and set the `max-width` and `max-height` of any logo image something like `300px` and `150px`, we get this:
![](http://spdr.me/aOAIIo+)

This same CSS works with other logo shapes without any adjustment required, e.g.: 
![](http://spdr.me/N9CIcc+)
![](http://spdr.me/jWoy62+)

This would also make it possible to make the logo URL a simple config option, rather than requiring a template override.

Or have I missed something? Is there a particular reason it has been done the way it has?

**Comment by ScopeyNZ** [comment]
Would you like to submit a PR?

**Comment by purplespider** [comment]
Certainly, just wanted to check the reasons for how it had been done using CSS variables in case I was missing something.

**Comment by ScopeyNZ** [comment]
Not sure, but the PR wouldn't hurt. I'll leave @Cheddam to merge it though 😛

**Comment by Cheddam** [comment]
@purplespider The only guidance I'd give is thorough testing in Internet Explorer 11 - its CSS Grid support is a little shaky, so in some cases `auto` doesn't act the same way as in other browsers. Happy to review a PR!

**Comment by purplespider** [comment]
@Cheddam How does this look? #52

**Comment by Cheddam** [comment]
@purplespider I've cherry-picked the fix into the `4.1` branch, and released [`4.1.1`](https://github.com/silverstripe/silverstripe-login-forms/releases/tag/4.1.1). Thanks again for your contribution!
