### ISSUE TITLE
Long Site title make login box wider

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-login-forms#68]
Replication steps:
- Change your site title to something very long
- Logout and access the login screen

Expected results: The site title on the login screen get broken into many lines
Actual results: The site title is displayed over one line and the login form wrapper expand to be the same width as the title

![image](https://user-images.githubusercontent.com/1168676/90570646-4692e500-e204-11ea-8bef-1e2be6bece38.png)

**Comment by maxime-rainville** [comment]
@silverstripeux

**Comment by emteknetnz** [comment]
Linked PR has been merged, closing issue

**Comment by emteknetnz** [comment]
New linked PR has been merged
