### ISSUE TITLE
Minor module release

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-login-forms#87]
Looking to have a minor release done on `4` so to make the [CMS branding changes](https://github.com/silverstripe/silverstripe-login-forms/pull/75) available, please!

**Comment by emteknetnz** [comment]
4.4.0 tag - https://github.com/silverstripe/silverstripe-login-forms/releases/tag/4.4.0

4 build https://travis-ci.com/github/silverstripe/silverstripe-login-forms/builds/222124290

4.4.0 build https://travis-ci.com/github/silverstripe/silverstripe-login-forms/builds/222454662
