### ISSUE TITLE
Inaccurate help text (move to popover)

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-login-forms#90]
### Overview
A new help icon and tooltip test was recently added to support users in using the 'keep me signed in' feature.

See: https://github.com/silverstripe/silverstripe-login-forms/pull/86

The wording added to this tooltip makes mention that "Authenticated devices can be managed in your profile.". This text will not always be accurate to a project with this module installed, as that functionality also relies on having another module installed (silverstripe/session-manager).

This wording needs to be updated to meet all use cases. At the same time, feedback from @clarkepaul on the original pull request was that a [popover would provide a better UX over a tooltip](https://github.com/silverstripe/silverstripe-login-forms/pull/86#issuecomment-817442718). This issue can focus on that too.

[Use this design as a reference for following tasks](https://projects.invisionapp.com/share/BN10MV40YMZT#/screens/448746237_Login_Forms_-_Keep_Me_Signed_In_V2).

So, to do:
1. Replace tooltip with a popover
2. Update the wording to remove reference to "Authenticated devices can be managed in your profile."

### Acceptance Criteria
- [x] The tooltip functionality is removed and replaced with a popover
- [x] The popover is called when the icon is clicked
- [x] Clicking outside of the popover will close it
- [x] The popover and checkbox wording is updated to meet the [following designs](https://projects.invisionapp.com/share/BN10MV40YMZT#/screens/448746237_Login_Forms_-_Keep_Me_Signed_In_V2) (also linked above)
- [x] Tabbing functionality can be used on the ? icon to trigger the popover
- [x] The "Need help?" link should align with the bottom of the Login title

### PRs
- [x] https://github.com/silverstripe/silverstripe-login-forms/pull/91
- [x] https://github.com/silverstripe/silverstripe-framework/pull/9918

**Comment by brynwhyman** [comment]
@clarkepaul I can't find the Invision link where the wording was updated, can you please help here?

**Comment by emteknetnz** [comment]
@clarkepaul popover without title, content only, alignment top, with default styling

![image](https://user-images.githubusercontent.com/4809037/114638979-e1ef4200-9d20-11eb-989c-b203bd18449c.png)

I'm not sure if we use popovers anywhere else on the site, so I'm not sure if this styling is consistent with other things or not

Let me know if you're happy with this, or if you'd like styling adjustments made, either:
a) globally (may have to be a seperate issue) or
b) specifically for this the login-forms popover

**Comment by clarkepaul** [comment]
Looks a little squashed at the top for some reason, missing some padding at the top which is normally there. If you take the heading out of the [one on our pattern library](https://silverstripe.github.io/silverstripe-admin/?selectedKind=Admin%2FPopoverField&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) it still has padding at the top. Otherwise looks right.

Actually can you compare the font size too, looks smaller (should equate to around 13px).

**Comment by emteknetnz** [comment]
@clarkepaul What should the heading text be?  Or are you saying no heading, just use the same top-padding as headings in pattern library?

**Comment by clarkepaul** [comment]
No heading, just the one in our pattern library has a heading in its example. When you remove the heading from the one in our pattern library it still has padding at the top of the popover of 12px (your example doesn't have that).

**Comment by emteknetnz** [comment]
OK sweet.  Given the pattern library popover looks sensible, and the login forms font-size is weird, I think it makes sense for me to not try to fix this globally (cos it already work correctly globally) and make some CSS adjustments in the login-forms module - does this sound alright?

**Comment by emteknetnz** [comment]
@clarkepaul How's this?

![image](https://user-images.githubusercontent.com/4809037/114658500-feea3c00-9d45-11eb-864e-e9eada55e5f7.png)

**Comment by emteknetnz** [comment]
Paul has approved design review (thumbs up emoji) though text still needs to be updated.

**Comment by emteknetnz** [comment]
@clarkepaul with updated text

I also noticed the AC of aligning the "Need help?" wasn't met, so I've updated.  Does this look good to you?

![image](https://user-images.githubusercontent.com/4809037/114815679-d1b39180-9e0a-11eb-9317-097f313072c7.png)

**Comment by brynwhyman** [comment]
@emteknetnz it doesn't look like the checkbox wording has changed in your PR either. This was in the original designs (and linked in this issue) but was originally missed.

**Comment by emteknetnz** [comment]
Updated

![image](https://user-images.githubusercontent.com/4809037/114942121-2c46ff00-9e98-11eb-94df-55dec7b15b93.png)

**Comment by clarkepaul** [comment]
Perfect visually! is that everything now incl. tabbing, clicking outside the popover?

**Comment by emteknetnz** [comment]
Here's a video showing tabbing and clicking outside the popover (sorry about the low encode quality)

https://www.youtube.com/watch?v=G5r7nNz4qbQ

Are you happy with this?

**Comment by maxime-rainville** [comment]
Did a peer review ... looks mostly OK aside from those translation strings being updated.

Probably just need to validate we want to ship this in a patch release instead of the next minor and get formal UX approval from Paul.

**Comment by brynwhyman** [comment]
It would be nice to get this into the patch release as it's refactoring some work done in https://github.com/silverstripe/silverstripe-login-forms/pull/86 (which is on `4.3`)
