### ISSUE TITLE
'Need help' link isn't always relevant

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-login-forms#93]
Following the latest release of this module, there's been enough feedback come through that the '[Need help' link](https://github.com/silverstripe/silverstripe-login-forms/blob/af1bf7a95530c90586d988f16865eee7dbf67d01/themes/login-forms/templates/Security.ss#L26) built into the template won't always be helpful.

Where projects use the login form for non-CMS members to authenticate, it is of no relevance to them to display a help link to the CMS Userhelp guides.

Options have been discussed to make the help link configurable depending on whether the developer wants to point the user to either the CMS Userhelp or some other support source, but this is unlikely to be top of mind to update and ultimately, providing help links for a login screen provides limited value.

This issue proposes the 'Need help' link is removed completely. 

### PRs
- [x] https://github.com/silverstripe/silverstripe-login-forms/pull/95

**Comment by brynwhyman** [comment]
cc @clarkepaul @madmatt

**Comment by madmatt** [comment]
Thanks for the consideration Bryn! I like the idea of there being the potential for a link, but maybe opt-in and developer controlled so it can be more easily used (or not) as the case may be. Either way though I'm happy with the decision <3

**Comment by emteknetnz** [comment]
@brynwhyman I just did a release of `4.4.2` - however I noticed that it didn't contain the fix above because it was targeted to `4` instead of `4.4` (technically it's a functionality change) - it would be slightly pushing it backporting this - do you want it released as `4.5.0`?

**Comment by maxime-rainville** [comment]
My instinct would be to cherry pick this change back into the 4.4 branch. It's just removing a label, so technically it doesn't change any API.

**Comment by brynwhyman** [comment]
> My instinct would be to cherry pick this change back into the 4.4 branch. It's just removing a label, so technically it doesn't change any API.

+1

**Comment by emteknetnz** [comment]
Cherry-picked to 4.4 and released [4.4.3](https://github.com/silverstripe/silverstripe-login-forms/releases/tag/4.4.3)
