### ISSUE TITLE
Login and lost password buttons appearing outside the form box

### ISSUE THREAD

**Issue by sig-peggy** [silverstripe/silverstripe-login-forms#94]
Using 4.4.1 with SilverStripe 4.8.0

On Firefox and Chrome, the 'Log in' button and 'I've lost my password' link are often, but not always, moving outside of the form box, overlapping with the silverstripe logo. The same thing happens on the Lost Password form. This seems to happen when the page is first accessed, but goes away if the page is refreshed.

![image](https://user-images.githubusercontent.com/82991689/122327481-061a0a00-cf82-11eb-8918-d3e0d7c5e0dc.png)
![image](https://user-images.githubusercontent.com/82991689/122327494-0ca88180-cf82-11eb-809e-2fcc25eb454c.png)

The .form class is set to `height: 100%` but with login-form__header and login-form__message above the form itself this pushes the bottom of the form off the end of the login-form.

**Comment by maxime-rainville** [comment]
@sig-peggy This doesn't look at all like the style for our buttons. I suspect you might have some of your frontend theme CSS leaking into the login page. Can you double check where the buttons are getting those styles from in your browser inspector?

**Comment by sig-peggy** [comment]
@maxime-rainville The only css files are:

- vendor/silverstripe/login-forms/client/dist/styles/bundle.css 
- vendor/silverstripe/admin/client/dist/styles/bundle.css
- vendor/silverstripe/login-forms/client/dist/styles/darkmode.css

It looks like the colours are coming directly from bootstrap without being replaced with any variables. The colour of the button comes from `--color-button-secondary-text:#0071c4;` which is in https://github.com/silverstripe/silverstripe-login-forms/blob/4/client/dist/styles/bundle.css

**Comment by maxime-rainville** [comment]
That's weird ... I'm not getting that at all on my local 
![image](https://user-images.githubusercontent.com/1168676/122501754-6de75800-d049-11eb-8d95-220303d33b33.png)

That's the styles applied to my button 
```css
.btn-primary, .btn-success, input[type="submit"] {
    background-color: #008a00;
    background-color: var(--color-button-primary-background);
    color: #fff;
    color: var(--color-button-primary-text);
    border: 0;
}
```

Looks like your login screen is trying to use the bootstrap secondary styles. Did you override the login-forms template in any way?

**Comment by sig-peggy** [comment]
@maxime-rainville Found the problem! Someone had made a change elsewhere that was making all the FormActions into `<button>` instead of `<input>`. Thanks for your help :)
