### ISSUE TITLE
Add dark mode support for help box

### ISSUE THREAD

**Issue by scott1702** [silverstripe/silverstripe-login-forms#96]
in dark mode the login form styling is light text on dark background, however this isn't the case for the help box

![image](https://user-images.githubusercontent.com/10215604/122337936-18507400-cf93-11eb-85b2-2adb3bedbd22.png)

# Pull request
- [x] https://github.com/silverstripe/silverstripe-login-forms/pull/98

**Comment by maxime-rainville** [comment]
@silverstripeux What should the help popup look like on the dark mode?

**Comment by clarkepaul** [comment]
@maxime-rainville you are highlighting a huge piece of work for @silverstripeux. This is a component which uses the same bg as other components so I'd need to take a stab in the dark as to what to use (unless I build out the complete dark mode patterns). I'll try to whip something up quickly but might not last long term... I'll get back to you.

**Comment by clarkepaul** [comment]
@maxime-rainville so what I'm thinking is to use the system grey variables as much as possible. From those I've selected grey 900 as the bg of components, grey 400 as the border of components (fifth option). 

![image](https://user-images.githubusercontent.com/555033/122693995-1981e980-d290-11eb-87bb-4880658729b9.png)

I also don't mind option 1 for smaller components but those colours don't work for larger areas like the CMS panel backgrounds, so for consistency using something like the fifth option is more flexible and consistent.

**Comment by clarkepaul** [comment]
hmm just comparing those colours to the ones used on Login Forms they are very different. I'm not sure where those colours came from, are they using some sort of variables in the CMS @maxime-rainville?

**Comment by clarkepaul** [comment]
I don't think we'd go down the path of introducing dark mode into the pattern library for some time. For a temporary measure use the same colours that are already used in the UI (whatever they may be). For example...
![image](https://user-images.githubusercontent.com/555033/122700596-b13b0400-d29f-11eb-993b-09b72249bf18.png)

**Comment by maxime-rainville** [comment]
Got a fix here https://github.com/silverstripe/silverstripe-login-forms/pull/98

**Comment by clarkepaul** [comment]
Fix looks good, got my seal of approval.
