### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-login-forms#97]
With https://github.com/silverstripe/silverstripe-login-forms/issues/93 closed, we should do a new module release to make this change available.

**Comment by emteknetnz** [comment]
Will tag once https://github.com/silverstripe/silverstripe-login-forms/pull/98 has been merged

**Comment by emteknetnz** [comment]
[Done](https://github.com/silverstripe/silverstripe-login-forms/releases/tag/4.4.3)
